# Root logger handlers
handlers = java.util.logging.FileHandler

# Log to 'logs/Graphy.log' file.
java.util.logging.FileHandler.pattern = logs/Graphy.%u.log

# Only accept INFO or above messages for the general log.
java.util.logging.FileHandler.level = FINEST

# Use Simple Formatter.
java.util.logging.FileHandler.formatter = dev.velocity71.Graphy.CustomFormatter

java.util.logging.FileHandler.limit = 5000000
java.util.logging.FileHandler.clount = 10

# Root logger granularity.
.level = FINEST

# Root logger granularity.
.level = FINEST
